---
- name: Setup Docker and Portainer
  hosts: dockernode
  become: true
  vars_files:
    - secrets.yaml
  vars:
    certbot_auto_renew: true
    certbot_auto_renew_user: root
    firewall_flush_rules_and_chains: false
    docker_users:
      - ansible

  roles:
    - geerlingguy.certbot
    - geerlingguy.docker

  tasks:
    - name: Install the latest version of python3-docker
      ansible.builtin.package:
        name:
          - python3-docker
        state: present

    - name: Install Certbot Cloudflare
      ansible.builtin.package:
        name: python3-certbot-dns-cloudflare
        state: present

    - name: Create Certbot folder - /etc/letsencrypt
      ansible.builtin.file:
        path: /etc/letsencrypt
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Certbot Template
      ansible.builtin.template:
        src: "dnscloudflare.ini.j2"
        dest: "/etc/letsencrypt/dnscloudflare.ini"
        owner: root
        group: root
        mode: "0600"

    - name: Certbot | Generate Certificate
      ansible.builtin.command: >
        certbot certonly --non-interactive --agree-tos --dns-cloudflare
        --dns-cloudflare-credentials /etc/letsencrypt/dnscloudflare.ini
        -m {{ certbot_mail }} -d {{ inventory_hostname }} -d *.
        {{ inventory_hostname }}
      args:
        creates: "/etc/letsencrypt/renewal/{{ inventory_hostname }}.conf"

    # docker worker nodes

    - name: Custom docker config
      ansible.builtin.template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        mode: "0644"
      notify: Restart Docker
      when: "'infra' not in group_names"

    - name: Get Portainer infra server
      ansible.builtin.set_fact:
        portainer_server: "{{ groups['infra'][0] }}"
      when: "'infra' not in group_names"

    - name: Check if endpoint already exists in Portainer
      ansible.builtin.uri:
        url: "http://{{ portainer_server }}:9000/api/endpoints"
        method: GET
        headers:
          X-API-Key: "{{ portainer_api_key }}"
        validate_certs: false
        status_code: [200]
      register: portainer_endpoints
      when: "'infra' not in group_names"
      delegate_to: localhost

    - name: Check if current host is registered
      ansible.builtin.set_fact:
        is_registered: "{{ portainer_endpoints.json | selectattr('Name', 'equalto', inventory_hostname) | list | length > 0 }}"
      when: "'infra' not in group_names"

    - name: Register agent with Portainer
      ansible.builtin.uri:
        url: "http://{{ portainer_server }}:9000/api/endpoints"
        method: POST
        headers:
          X-API-Key: "{{ portainer_api_key }}"
          Content-Type: "application/json"
        body_format: form-multipart
        body:
          Name: "{{ inventory_hostname }}"
          EndpointCreationType: "2"
          URL: "tcp://{{ inventory_hostname }}:9001"
          ContainerEngine: "docker"
          GroupID: "1"
          TLS: "true"
          TLSSkipVerify: "true"
          TLSSkipClientVerify: "true"
        validate_certs: false
        status_code: [200, 201]
      when: "'infra' not in group_names and not is_registered"
      delegate_to: localhost

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
