---
- name: Setup Docker and Portainer
  hosts: dockernode
  become: true
  vars_files:
    - secrets.yaml
  vars:
    firewall_flush_rules_and_chains: false

  roles:
    - certbot_local
    - geerlingguy.docker

  pre_tasks:
    - name: Install the latest version of python3-docker
      ansible.builtin.package:
        name:
          - python3-docker
          - gnupg2
        state: present

  tasks:
    - name: Certbot | Generate Certificate
      ansible.builtin.command:
        argv:
          - certbot
          - certonly
          - --non-interactive
          - --agree-tos
          - --dns-cloudflare
          - --dns-cloudflare-credentials
          - /etc/letsencrypt/dnscloudflare.ini
          - -m
          - "{{ certbot_mail }}"
          - -d
          - "{{ inventory_hostname }}"
          - -d
          - "*.{{ inventory_hostname }}"
      args:
        creates: "/etc/letsencrypt/renewal/{{ inventory_hostname }}.conf"

    # docker worker nodes

    - name: Custom docker config
      ansible.builtin.template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        mode: "0644"
      notify: Restart Docker
      when: "'infra' not in group_names"

    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Enable and start firewalld service
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started

    - name: Set default zone to drop
      ansible.posix.firewalld:
        zone: drop
        state: present
        permanent: true
        immediate: true

    - name: Allow SSH in drop zone
      ansible.posix.firewalld:
        zone: drop
        service: ssh
        state: enabled
        permanent: true
        immediate: true

    - name: Allow HTTP in drop zone
      ansible.posix.firewalld:
        zone: drop
        service: http
        state: enabled
        permanent: true
        immediate: true

    - name: Allow HTTPS in drop zone
      ansible.posix.firewalld:
        zone: drop
        service: https
        state: enabled
        permanent: true
        immediate: true

    - name: Allow HTTP/3 (UDP 443) in drop zone
      ansible.posix.firewalld:
        zone: drop
        port: 443/udp
        state: enabled
        permanent: true
        immediate: true

    - name: Create compose-ports directory
      ansible.builtin.file:
        path: /etc/firewalld/compose-ports
        state: directory
        mode: "0755"

  handlers:
    - name: Import common handlers
      ansible.builtin.import_tasks: handlers/main.yml
