---
- name: Setup Docker and Portainer
  hosts: dockernode
  become: true
  vars_files:
    - secrets.yaml
  vars:
    firewall_flush_rules_and_chains: false

  roles:
    - certbot_local
    - geerlingguy.docker

  pre_tasks:
    - name: Install the latest version of python3-docker
      ansible.builtin.package:
        name:
          - python3-docker
          - gnupg2
        state: present

  tasks:
    - name: Certbot | Generate Certificate
      ansible.builtin.command:
        argv:
          - certbot
          - certonly
          - --non-interactive
          - --agree-tos
          - --dns-cloudflare
          - --dns-cloudflare-credentials
          - /etc/letsencrypt/dnscloudflare.ini
          - -m
          - "{{ certbot_mail }}"
          - -d
          - "{{ inventory_hostname }}"
          - -d
          - "*.{{ inventory_hostname }}"
      args:
        creates: "/etc/letsencrypt/renewal/{{ inventory_hostname }}.conf"

    # docker worker nodes

    - name: Custom docker config
      ansible.builtin.template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        mode: "0644"
      notify: Restart Docker
      when: "'infra' not in group_names"

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
