---
- name: Migrate Docker application data from /datas/apps to /opt/apps
  hosts: dockernode
  become: true
  gather_facts: false
  vars:
    legacy_root: /datas/apps
    new_root: /opt/apps
    migration_sentinel: /opt/apps/.migration_done
  tasks:
    - name: Ensure required packages (python3-docker, rsync) are present
      ansible.builtin.package:
        name:
          - python3-docker
          - rsync
        state: present
        update_cache: true

    - name: Ensure new root exists
      ansible.builtin.file:
        path: "{{ new_root }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Stat legacy root
      ansible.builtin.stat:
        path: "{{ legacy_root }}"
      register: legacy_stat

    - name: Stat migration sentinel
      ansible.builtin.stat:
        path: "{{ migration_sentinel }}"
      register: sentinel_stat

    - name: Find deployed compose directories
      ansible.builtin.find:
        paths: compose
        recurse: false
        file_type: directory
      register: compose_dirs
      when: legacy_stat.stat.exists and not sentinel_stat.stat.exists

    - name: Stop all compose stacks (pre-migration)
      community.docker.docker_compose_v2:
        project_src: "{{ item.path }}"
        state: stopped
      loop: "{{ compose_dirs.files | default([]) }}"
      when: legacy_stat.stat.exists and not sentinel_stat.stat.exists
      ignore_errors: true

    - name: Migrate data (rsync then archive legacy root)
      ansible.builtin.shell: |
        set -euo pipefail
        rsync -a --delete --ignore-errors "{{ legacy_root }}/" "{{ new_root }}/"
        mv "{{ legacy_root }}" "{{ legacy_root }}.old_$(date +%Y%m%d%H%M%S)"
      args:
        executable: /bin/bash
      when: legacy_stat.stat.exists and not legacy_stat.stat.islnk and not sentinel_stat.stat.exists

    - name: Create migration sentinel
      ansible.builtin.file:
        path: "{{ migration_sentinel }}"
        state: touch
        mode: "0755"
        owner: root
        group: root
      when: legacy_stat.stat.exists and not sentinel_stat.stat.exists

    - name: Display migration summary
      ansible.builtin.debug:
        msg: >-
          Migration executed. Legacy root {{ legacy_root }} moved and symlinked. Redeploy compose with docker-deploy.yml.
      when: legacy_stat.stat.exists and not sentinel_stat.stat.exists

- name: Exec docker deploy
  import_playbook: docker-deploy.yml
