---
- name: Deploy docker-compose
  hosts: dockernode
  become: true
  vars_files:
    - secrets.yaml
  vars:
    compose_dir: compose
    compose_pattern: "*.j2"
    compose_suffix: ".compose.j2"
    deploy_service: "all"  # Set to specific service name to deploy only that service, or "all" for all services
  tasks:
    - name: Create folder - compose
      ansible.builtin.file:
        path: "{{ compose_dir }}"
        state: directory
        mode: "0775"

    - name: Create folder - datas
      ansible.builtin.file:
        path: "/opt/apps"
        state: directory
        recurse: true

    - name: Find local compose files
      ansible.builtin.find:
        paths: "{{ compose_dir }}"
        recurse: false
        patterns: "{{ deploy_service + compose_suffix if deploy_service != 'all' else compose_pattern }}"
      register: local_compose
      delegate_to: localhost

    - name: Find host compose files
      ansible.builtin.find:
        paths: "{{ playbook_dir }}/{{ compose_dir }}/{{ inventory_hostname }}"
        recurse: false
        patterns: "{{ deploy_service + compose_suffix if deploy_service != 'all' else compose_pattern }}"
      register: host_compose
      delegate_to: localhost

    - name: Copy global compose files
      ansible.builtin.include_tasks: tasks/copy-compose.yml
      loop: "{{ local_compose.files | map(attribute='path') | flatten }}"

    - name: Copy host reserved docker-compose
      ansible.builtin.include_tasks: tasks/copy-compose.yml
      loop: "{{ host_compose.files | map(attribute='path') | flatten }}"

    - name: Find deployed compose files
      ansible.builtin.find:
        paths: "{{ compose_dir }}"
        recurse: false
        file_type: directory
      register: deployed_compose

    - name: Clean deployed compose
      ansible.builtin.set_fact:
        proper_deployed_compose: "{{ deployed_compose.files | map(attribute='path') | map('basename') | flatten }}"

    - name: Clean local compose files
      ansible.builtin.set_fact:
        proper_local_compose: "{{ local_compose.files | map(attribute='path') | map('basename') | map('regex_replace', compose_suffix, '') | flatten }}"

    - name: Clean host compose files
      ansible.builtin.set_fact:
        proper_host_compose: "{{ host_compose.files | map(attribute='path') | map('basename') | map('regex_replace', compose_suffix, '') | flatten }}"

    - name: Remove old compose files
      ansible.builtin.include_tasks: tasks/remove-compose.yml
      loop: "{{ proper_deployed_compose | difference(proper_local_compose) | difference(proper_host_compose) }}"
      when: deploy_service == 'all'

    - name: Find compose files at root of compose directory
      ansible.builtin.find:
        paths: "{{ compose_dir }}"
        recurse: false
        patterns: "*.compose"
        file_type: file
      register: compose_yaml_files

    - name: Delete compose files at root of compose directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ compose_yaml_files.files }}"
      when: 
        - compose_yaml_files.files | length > 0
        - deploy_service == 'all'

    - name: Clean up dangling Docker images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true
      register: docker_prune_result
      when: deploy_service == 'all'

    - name: Display pruned images info
      ansible.builtin.debug:
        msg: "Reclaimed {{ docker_prune_result.space_reclaimed | human_readable }} from dangling images"
      when: docker_prune_result.space_reclaimed is defined and docker_prune_result.space_reclaimed > 0
