---
- name: Setup firewalld firewall
  hosts: all
  become: true

  tasks:
    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Enable and start firewalld service
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started

    - name: Enable and start nftables service
      ansible.builtin.systemd:
        name: nftables
        enabled: true
        state: started

    - name: Set default zone to internal
      ansible.builtin.command:
        cmd: firewall-cmd --set-default-zone=internal
      tags:
        - skip_ansible_lint

    - name: Allow SSH in internal zone
      ansible.posix.firewalld:
        zone: internal
        service: ssh
        state: enabled
        permanent: true
        immediate: true

    - name: Reboot host to apply firewall changes
      ansible.builtin.reboot:
        msg: "Reboot initiated by firewall.playbook"
        reboot_timeout: 600

  handlers:
    - name: Import common handlers
      ansible.builtin.import_tasks: handlers/main.yml
