---

all:
   vars:
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: root
      ansible_private_key_file: ~/.ssh/poppy
   hosts:
      pve1.moot.ovh:
         ansible_host: 10.0.1.1
      ipa.moot.ovh:
         ansible_host: 10.0.1.101
      pve2.moot.ovh:
         ansible_host: 10.0.2.1
      sys10.moot.ovh:
         ansible_host: 10.0.1.110
      sys11.moot.ovh:
         ansible_host: 10.0.1.111
      sys12.moot.ovh:
         ansible_host: 10.0.2.109
      sys13.moot.ovh:
         ansible_host: 10.0.1.113