---
- name: Initialize SSH and Base Setup
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - secrets.yaml
  vars:
    unifi_udm_host: "unifi.moot.ovh"
    do_pkg_update: true
    do_pkg_upgrade: true
    do_reboot: true

  pre_tasks:
    - name: Bootstrap | Ensure Python 3 is installed
      ansible.builtin.raw: |
        if command -v python3 >/dev/null 2>&1; then
          exit 0
        fi
        if command -v apt-get >/dev/null 2>&1; then
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -y && apt-get install -y python3
        elif command -v dnf >/dev/null 2>&1; then
          dnf install -y python3
        elif command -v yum >/dev/null 2>&1; then
          yum install -y python3
        elif command -v zypper >/dev/null 2>&1; then
          zypper -n install python3
        elif command -v apk >/dev/null 2>&1; then
          apk add --no-cache python3
        else
          echo "No supported package manager found to install python3" >&2
          exit 1
        fi
      changed_when: true
      become: true

    - name: Bootstrap | Gather facts after Python installation
      ansible.builtin.setup:

    - name: PKG | Update package manager cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
      when:
        - do_pkg_update | bool
        - ansible_facts.os_family == 'Debian'

    - name: PKG | Update package manager cache (RedHat/Fedora)
      ansible.builtin.dnf:
        update_cache: true
      when:
        - do_pkg_update | bool
        - ansible_facts.os_family in ['RedHat']

    - name: PKG | Upgrade system packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
      when:
        - do_pkg_upgrade | bool
        - ansible_facts.os_family == 'Debian'

    - name: PKG | Upgrade system packages (RedHat/Fedora)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when:
        - do_pkg_upgrade | bool
        - ansible_facts.os_family in ['RedHat']

    - name: SSH | Add remote host key to local known_hosts
      ansible.builtin.command: "ssh-keyscan -t ecdsa,ed25519 {{ inventory_hostname }},{{ ansible_default_ipv4.address }}"
      register: ssh_keyscan
      changed_when: false
      delegate_to: localhost

    - name: SSH | Write host key to known_hosts
      ansible.builtin.known_hosts:
        path: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
        name: "{{ inventory_hostname }}"
        key: "{{ ssh_keyscan.stdout }}"
      delegate_to: localhost

  tasks:
    - name: Install base packages
      ansible.builtin.package:
        name:
          - sudo
          - nano
          - screen
          - jq
          - yq
          - cracklib-dicts
        state: present
    - name: Make sure we have a 'wheel' group
      ansible.builtin.group:
        name: wheel
        state: present
    - name: Add the user 'ansible'
      ansible.builtin.user:
        name: ansible
        groups: wheel
        append: true
        shell: /bin/bash
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/ansiblekey.pub') }}"

    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Ensure hostname set
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Ensure hostname is in /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: "^{{ ansible_default_ipv4.address }}.+$"
        line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

    - name: Lock ansible users passwd
      ansible.builtin.user:
        name: ansible
        state: present
        password_lock: true

    - name: UDM | Fetch existing DNS records
      ansible.builtin.uri:
        url: "https://{{ unifi_udm_host }}/proxy/network/v2/api/site/default/static-dns"
        method: GET
        status_code: 200
        headers:
          X-API-Key: "{{ unifi_api_key }}"
      register: unifi_dns_records
      tags: [dns]

    - name: UDM | Determine if record exists
      ansible.builtin.set_fact:
        unifi_dns_exists: "{{ (unifi_dns_records.json | default([])) | selectattr('key', 'equalto', inventory_hostname) | list | length > 0 }}"
      when: unifi_dns_records is defined
      tags: [dns]

    - name: UDM | Create DNS A record
      ansible.builtin.uri:
        url: "https://{{ unifi_udm_host }}/proxy/network/v2/api/site/default/static-dns"
        method: POST
        body_format: json
        body:
          key: "{{ inventory_hostname }}"
          record_type: "A"
          value: "{{ ansible_default_ipv4.address }}"
          enabled: true
        status_code: [200, 201]
        headers:
          X-API-Key: "{{ unifi_api_key }}"
      when: unifi_dns_exists is defined and (not unifi_dns_exists)
      tags: [dns]

    - name: UDM | Determine if wildcard record exists
      ansible.builtin.set_fact:
        unifi_dns_wildcard_exists: "{{ (unifi_dns_records.json | default([])) | selectattr('key', 'equalto', '*.' + inventory_hostname) | list | length > 0 }}"
      when: unifi_dns_records is defined
      tags: [dns]

    - name: UDM | Create wildcard DNS A record
      ansible.builtin.uri:
        url: "https://{{ unifi_udm_host }}/proxy/network/v2/api/site/default/static-dns"
        method: POST
        body_format: json
        body:
          key: "*.{{ inventory_hostname }}"
          record_type: "A"
          value: "{{ ansible_default_ipv4.address }}"
          enabled: true
        status_code: [200, 201]
        headers:
          X-API-Key: "{{ unifi_api_key }}"
      when: unifi_dns_wildcard_exists is defined and (not unifi_dns_wildcard_exists)
      tags: [dns]

    - name: Activate SSHD
      ansible.builtin.systemd_service:
        name: "sshd.socket"
        enabled: true
        state: "started"

  post_tasks:
    - name: Reboot | Reboot host if requested
      ansible.builtin.reboot:
        msg: "Reboot initiated by initssh.playbook"
        reboot_timeout: 600
      when: do_reboot | bool
