--- # noqa: run-once[play]
- name: Install NAS Arr
  hosts: nas, datas.moot.ovh
  strategy: free
  serial: 2
  become: true
  vars_files:
    - secrets.yaml

  vars:
    dls_base: /datas/dls

    dls_owner: "media"
    dls_group: "media"

    dls_directories:
      - "{{ dls_base }}/media/movies"
      - "{{ dls_base }}/media/series"
      - "{{ dls_base }}/media/others"

      - "{{ dls_base }}/bt/movies"
      - "{{ dls_base }}/bt/series"

      - "{{ dls_base }}/ddl"
      - "{{ dls_base }}/ddl/downloads"

      - "{{ dls_base }}/usenet/movies"
      - "{{ dls_base }}/usenet/series"

      - "{{ dls_base }}/games"
      - "{{ dls_base }}/others"

  tasks:
    - name: Create DLS directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ dls_owner }}"
        group: "{{ dls_group }}"
      loop: "{{ dls_directories }}"
      tags: directory

    - name: Install arr python packages
      ansible.builtin.pip:
        name:
          - sonarr-py
          - radarr-py
          - prowlarr-py
      tags: prerequisites
      delegate_to: localhost

    - name: Check if Radarr config exists
      ansible.builtin.stat:
        path: /opt/apps/arr/radarr/data/config.xml
      register: radarr_config_stat
      tags: radarr

    - name: Get Radarr API key
      community.general.xml:
        path: /opt/apps/arr/radarr/data/config.xml
        xpath: /Config/ApiKey
        content: text
      register: radarr_api_key_xml
      when: radarr_config_stat.stat.exists
      tags: radarr

    - name: Set Radarr API key fact
      ansible.builtin.set_fact:
        radarr_api_key: "{{ radarr_api_key_xml.matches[0].ApiKey }}"
      when: radarr_config_stat.stat.exists
      tags: radarr

    - name: Create download client
      devopsarr.radarr.radarr_download_client:
        radarr_api_key: "{{ radarr_api_key }}"
        radarr_url: "http://{{ inventory_hostname }}:7878"
        name: "rdt"
        enable: true
        protocol: "torrent"
        config_contract: "QBittorrentSettings"
        implementation: "QBittorrent"
        update_secrets: true
        priority: 1
        fields: [
          {"name": "host", "value": "{{ inventory_hostname }}"},
          {"name": "port", "value": 6500},
          {"name": "username", "value": "root"},
          {"name": "password", "value": ""},
          {"name": "movieCategory", "value": "movies"},
        ]
      when: radarr_config_stat.stat.exists
      tags: radarr
      delegate_to: localhost

    - name: Check if Sonarr config exists
      ansible.builtin.stat:
        path: /opt/apps/arr/sonarr/data/config.xml
      register: sonarr_config_stat
      tags: sonarr

    - name: Get Sonarr API key
      community.general.xml:
        path: /opt/apps/arr/sonarr/data/config.xml
        xpath: /Config/ApiKey
        content: text
      register: sonarr_api_key_xml
      when: sonarr_config_stat.stat.exists
      tags: sonarr

    - name: Set Sonarr API key fact
      ansible.builtin.set_fact:
        sonarr_api_key: "{{ sonarr_api_key_xml.matches[0].ApiKey }}"
      when: sonarr_config_stat.stat.exists
      tags: sonarr

    - name: Create download client
      devopsarr.sonarr.sonarr_download_client:
        sonarr_api_key: "{{ sonarr_api_key }}"
        sonarr_url: "http://{{ inventory_hostname }}:8989"
        name: "rdt"
        enable: true
        protocol: "torrent"
        config_contract: "QBittorrentSettings"
        implementation: "QBittorrent"
        update_secrets: true
        priority: 1
        fields: [
          {"name": "host", "value": "{{ inventory_hostname }}"},
          {"name": "port", "value": 6500},
          {"name": "username", "value": "root"},
          {"name": "password", "value": ""},
          {"name": "tvCategory", "value": "series"},
        ]
      when: sonarr_config_stat.stat.exists
      tags: sonarr
      delegate_to: localhost
