---
- name: Install NAS server
  hosts: nas
  become: true
  vars_files:
    - secrets.yaml
  vars:
    # Centralized group definitions with GIDs
    groups_config:
      - name: admins
        gid: 10000
      - name: apps
        gid: 10011
      - name: media
        gid: 10008

    # Centralized user definitions with UIDs
    users_config:
      - name: poppy
        uid: 10001
        groups:
          - admins
          - media
        is_admin: true
        is_system: false
      - name: cookiesochocola
        uid: 10012
        groups:
          - media
        is_admin: false
        is_system: false
      - name: media
        uid: 10010
        groups:
          - media
          - apps
        is_admin: false
        is_system: true

    # Legacy references (computed from config)
    admin_group: admins
    apps_group: apps
    media_group: media
    localgroups: "{{ groups_config | map(attribute='name') | list }}"
    users: "{{ users_config | rejectattr('is_system') | map(attribute='name') | list }}"
    adminusers: "{{ users_config | selectattr('is_admin') | map(attribute='name') | list }}"
    sysusers: "{{ users_config | selectattr('is_system') | map(attribute='name') | list }}"
    docker_users:
      - ansible

  tasks:
    - name: Install NFS server (Debian/Ubuntu)
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
      when: ansible_facts.os_family == 'Debian'

    - name: Install NFS server (RedHat/Fedora)
      ansible.builtin.dnf:
        name: nfs-utils
        state: present
      when: ansible_facts.os_family in ['RedHat']
    - name: Install SMB server
      ansible.builtin.package:
        name: samba
        state: present

    - name: Add smb.conf
      ansible.builtin.copy:
        src: files/smb.conf
        dest: /etc/samba/smb.conf
        mode: '0644'

    - name: Activate SMBD
      ansible.builtin.systemd_service:
        name: "smb"
        enabled: true
        state: "started"

    - name: "Create groups"
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
      loop: "{{ groups_config }}"

    - name: Gather existing local users
      ansible.builtin.getent:
        database: passwd
      register: passwd_db

    - name: Build existing usernames list
      ansible.builtin.set_fact:
        existing_usernames: "{{ passwd_db.ansible_facts.getent_passwd.keys() | list if passwd_db.ansible_facts.getent_passwd is defined else [] }}"

    - name: "Create user accounts"
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        append: true
        update_password: "on_create"
        password: "{{ accountdefaultpwd }}"
        groups: "{{ item.groups | join(',') }}"
        shell: /bin/bash
      loop: "{{ users_config | rejectattr('is_system') | list }}"
      register: accounts

    - name: Force change password on newly created users
      ansible.builtin.command: "chage -d 0 {{ item.item.name }}"
      when:
        - item.changed
        - item.item.name not in existing_usernames
      with_items: "{{ accounts.results }}"
      changed_when: true
      tags:
        - skip_ansible_lint

    - name: Fetch current smbpasswd users
      ansible.builtin.command: /usr/bin/pdbedit -L
      changed_when: false
      register: pdb_users

    - name: Create smbuser
      ansible.builtin.command: "/usr/bin/smbpasswd -n -a {{ item }}"
      when: item not in pdb_users.stdout
      with_items: "{{ users }}"
      changed_when: true

    - name: "Create system user"
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        append: true
        password_lock: true
        system: true
        group: "{{ item.groups[0] }}"
        groups: "{{ item.groups[1:] | join(',') if item.groups | length > 1 else omit }}"
      loop: "{{ users_config | selectattr('is_system') | list }}"

    - name: Check for ssh pub keys
      ansible.builtin.stat:
        path: "{{ 'files/' + item + '.pub' }}"
      delegate_to: localhost
      register: path_to_file_stat
      with_items: "{{ users }}"

    - name: Add authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.item }}"
        key: "{{ lookup('file', item.invocation.module_args.path) }}"
      with_items: "{{ path_to_file_stat.results }}"
      when: item.stat.exists

    - name: Allow poppy to SUDO All
      community.general.sudoers:
        name: allow-poppy
        state: present
        nopassword: false
        user: poppy
        commands: ALL

    - name: Install ACL
      ansible.builtin.package:
        name: acl
        state: present

    - name: Copy manage-share
      ansible.builtin.copy:
        src: files/manage-share.sh
        dest: /srv/manage-share.sh
        mode: '0744'

    - name: Copy mkhomedir
      ansible.builtin.copy:
        src: files/mkhomedir.sh
        dest: /srv/mkhomedir.sh
        mode: '0744'

    - name: Create /datas
      ansible.builtin.file:
        path: /datas
        state: directory
        mode: '0775'

    - name: Create /datas/usershare
      ansible.builtin.file:
        path: /datas/usershare
        state: directory
        mode: '0775'

    - name: Set Global ACL
      ansible.posix.acl:
        path: /datas
        default: true
        recursive: true
        state: present
        entity: "{{ admin_group }}"
        etype: group
        permissions: rwX

    - name: Create traefik network
      community.docker.docker_network:
        name: traefik
        driver: bridge
