---
- name: Create LXC from images.linuxcontainers.org
  hosts: pve2.moot.ovh
  become: true
  vars:
    # Required
    lxc_id: 200
    lxc_hostname: demo-ct

    # Image selection
    distro: ubuntu # ubuntu|debian|alpine|fedora|archlinux|...
    release: noble # e.g. noble|jammy|bookworm|alpine-3.19|...
    arch: amd64 # amd64|arm64|armhf|...
    variant: default # default|minimal|cloud

    # Proxmox config
    storage: local-lvm # storage for rootfs
    disk_size_gb: 8 # rootfs size in GB
    memory_mb: 2048 # RAM in MB
    cores: 2 # vCPU cores
    bridge: vmbr0 # network bridge
    ipv4: dhcp # 'dhcp' or CIDR like 10.0.2.105/20
    gateway4: "" # optional when using static IPv4
    unprivileged: false # privileged by default

    # SSH key (optional). If provided, must be a path on the Proxmox host
    ssh_public_key_path: "" # e.g. /root/.ssh/authorized_keys; defaults to files/poppy.pub
    lxc_user: "poppy"

    # Internals
    template_dir: "/var/lib/vz/template/cache"
    streams_url: "http://images.linuxcontainers.org/streams/v1/images.json"
    streams_cache: "{{ template_dir }}/images.json"
    force_streams_refresh: false
    dest_path: "{{ template_dir }}/{{ distro }}-{{ release }}-{{ arch }}-{{ variant }}-rootfs.tar.xz"

  tasks:
    - name: Build net0 configuration
      ansible.builtin.set_fact:
        net0: >-
          name=eth0,bridge={{ bridge }},ip={{ ipv4 }},ip6=auto{{ (",gw=" + gateway4) if (gateway4 | length > 0 and ipv4 != 'dhcp') else '' }}
        ssh_key_path_host: "{{ ssh_public_key_path if (ssh_public_key_path | length > 0) else '/root/.ssh/poppy.pub' }}"

    - name: Ensure template directory exists
      ansible.builtin.file:
        path: "{{ template_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure default SSH key present on host when not provided
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/poppy.pub"
        dest: "/root/.ssh/poppy.pub"
        mode: "0644"
      when: ssh_public_key_path | length == 0

    - name: Check streams cache file
      ansible.builtin.stat:
        path: "{{ streams_cache }}"
      register: streams_stat

    - name: Refresh streams cache if missing or older than 1 day or forced
      ansible.builtin.get_url:
        url: "{{ streams_url }}"
        dest: "{{ streams_cache }}"
        mode: "0644"
        force: true
      when: force_streams_refresh | bool or (not streams_stat.stat.exists) or ((ansible_date_time.epoch | int) - (streams_stat.stat.mtime | default(0) | int) > 86400)

    - name: Read streams cache
      ansible.builtin.slurp:
        path: "{{ streams_cache }}"
      register: streams_content

    - name: Parse streams JSON
      ansible.builtin.set_fact:
        streams_json: "{{ streams_content.content | b64decode | from_json }}"

    - name: Build image key
      ansible.builtin.set_fact:
        image_key: "{{ distro }}:{{ release }}:{{ arch }}:{{ variant }}"
        selected_url: ""

    - name: Select rootfs URL from streams
      ansible.builtin.set_fact:
        selected_url: 'http://images.linuxcontainers.org/{{ streams_json.products[image_key].versions | dict2items | sort(attribute=''key'', reverse=True) | first | json_query(''value.items."root.tar.xz".path'') | default('''') }}'
      when: streams_json is defined and 'products' in streams_json and image_key in streams_json.products

    - name: Fallback to direct current URL if selection failed
      ansible.builtin.set_fact:
        selected_url: "http://images.linuxcontainers.org/images/{{ distro }}/{{ release }}/{{ arch }}/{{ variant }}/current/rootfs.tar.xz"
      when: selected_url is defined and selected_url | length == 0

    - name: Download LXC rootfs from selected URL
      ansible.builtin.stat:
        path: "{{ dest_path }}"
      register: lxc_rootfs_stat

    - name: Decide if rootfs needs download
      ansible.builtin.set_fact:
        download_rootfs: "{{ (not lxc_rootfs_stat.stat.exists) or ((ansible_date_time.epoch | int) - (lxc_rootfs_stat.stat.mtime | default(0) | int) > 86400) }}"

    - name: Download LXC rootfs from selected URL
      ansible.builtin.get_url:
        url: "{{ selected_url }}"
        dest: "{{ dest_path }}"
        mode: "0644"
        force: true
      when: download_rootfs | bool

    - name: Read SSH public key content from host
      ansible.builtin.slurp:
        path: "{{ ssh_key_path_host }}"
      register: lxc_pubkey
      when: ssh_key_path_host | length > 0

    - name: Check if LXC container already exists
      ansible.builtin.command:
        cmd: pct status {{ lxc_id }}
      register: lxc_exists
      failed_when: false
      changed_when: false

    - name: Create LXC container from downloaded image
      ansible.builtin.command:
        cmd: >-
          pct create {{ lxc_id }} {{ dest_path }}
          --hostname {{ lxc_hostname }}
          --memory {{ memory_mb }}
          --swap 0
          --cores {{ cores }}
          --rootfs {{ storage }}:{{ disk_size_gb }}
          --net0 {{ net0 }}
          --ostype {{ distro }}
          --onboot 1
          --unprivileged {{ 1 if unprivileged else 0 }}
          {{ '--ssh-public-keys ' + ssh_key_path_host if ssh_key_path_host | length > 0 else '' }}
      args:
        creates: "/etc/pve/lxc/{{ lxc_id }}.conf"
      when: lxc_exists.rc != 0

    - name: Start LXC container
      ansible.builtin.command:
        cmd: pct start {{ lxc_id }}
      register: lxc_start
      failed_when: false
      changed_when: lxc_start.rc == 0

    - name: Ensure user exists inside container
      ansible.builtin.command:
        cmd: pct exec {{ lxc_id }} -- bash -c "id -u {{ lxc_user }} >/dev/null 2>&1 || useradd -m {{ lxc_user }}"
      register: lxc_user_create
      changed_when: lxc_user_create.rc == 0 and (lxc_user_create.stdout | default('')) | length > 0
      failed_when: lxc_user_create.rc != 0 and 'exists' not in (lxc_user_create.stderr | default(''))

    - name: Ensure .ssh directory exists for user
      ansible.builtin.command:
        cmd: pct exec {{ lxc_id }} -- bash -c "install -d -m 700 /home/{{ lxc_user }}/.ssh && chown {{ lxc_user }}:{{ lxc_user }} /home/{{ lxc_user }}/.ssh"
      changed_when: true

    - name: Install authorized_keys for user
      ansible.builtin.command:
        cmd: >-
          pct exec {{ lxc_id }} -- bash -c "echo {{ lxc_pubkey.content | b64decode | quote }} > /home/{{ lxc_user }}/.ssh/authorized_keys && chmod 600 /home/{{ lxc_user }}/.ssh/authorized_keys && chown {{ lxc_user }}:{{ lxc_user }} /home/{{ lxc_user }}/.ssh/authorized_keys"
      when: lxc_pubkey is defined
      changed_when: true

    - name: Sleep briefly for IP discovery
      ansible.builtin.pause:
        seconds: 2

    - name: Try to get container IP (best-effort)
      ansible.builtin.command:
        cmd: >-
          pct exec {{ lxc_id }} -- bash -c "hostname -I 2>/dev/null | awk '{print $1}'"
      register: ct_ip
      failed_when: false
      changed_when: false

    - name: Show summary
      ansible.builtin.debug:
        msg: |
          Created LXC container:
            VMID:       {{ lxc_id }}
            Hostname:   {{ lxc_hostname }}
            Storage:    {{ storage }}:{{ disk_size_gb }}G
            Memory:     {{ memory_mb }} MB
            Cores:      {{ cores }}
            Bridge:     {{ bridge }}
            IPv4 (req): {{ ipv4 }}{{ '  gw=' + gateway4 if gateway4 | length > 0 else '' }}
            IPv4 (det): {{ ct_ip.stdout | default('') }}
            Template:   {{ dest_path }}

          Tips:
            pct console {{ lxc_id }}
            pct exec {{ lxc_id }} -- bash
