# from galaxy

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.firewall
  - name: geerlingguy.security
  - name: geerlingguy.clamav
  - name: geerlingguy.pip
  - name: sbaerlocher.qemu-guest-agent
  - name: robertdebock.haveged
  - name: exploide.dnf-automatic
  - name: robertdebock.fail2ban
  - name: hudecof.banners
  - name: jgeusebroek.sysstat
  - name: andrewrothstein.screen
  - name: dev-sec.os-hardening
  - name: dev-sec.ssh-hardening

collections:
  - name: community.docker
  - name: community.general
  - name: ansible.posix
  - name: devsec.hardening
  - name: devopsarr.sonarr
  - name: devopsarr.prowlarr
  - name: devopsarr.radarr
