---

all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansiblekey
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    ipa.moot.ovh:

  children:
    dockernode:
      hosts:
        acc.moot.ovh:
        sys11.moot.ovh:
        sys12.moot.ovh:
        test.moot.ovh:
      children:
        frigate:
          hosts:
            frigate.moot.ovh:
        dockerregistry:
          hosts:
            sys10.moot.ovh:
        nas:
          hosts:
            test.moot.ovh:
            
    pveservers:
      hosts:
        pve1.moot.ovh:
        pve2.moot.ovh:
